### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by d1runberg** [sphero-inc/sphero-sdk-microbit-makecode#1]
I have imported the package and written a basic drive forward example, uploaded to my micro:bit and hooked up via USB to RVR. Nothing seems to work, is there something I am missing for controlling RVR with m:b + makeCode?

[My Example](https://makecode.microbit.org/_0PK2rvcY13Hj)

**Comment by meganrobinson22** [comment]
Hey d1runberg, thanks for reaching out!

I uploaded your example program to my micro:bit and was able to successfully run it on my RVR, so there are two possibilities that come to mind that might explain why it didn't work for you:
* Did you download the Sphero Edu app and update your RVR's firmware before you tried running your program? If you don't update the firmware after you take RVR out of the box, it remains in a locked state, which would explain why nothing happened!
* Another possibility (and one we actually ran into a lot during development!) is that you need to use a different USB cable. Most Sphero USB cables transfer only power and not data since they're meant for charging. We also saw inconsistent results with the USB cable that comes with the micro:bit, so if you have any other USB cables try one of those!

If these suggestions don't work please let me know and we'll keep working to figure it out :)

**Comment by d1runberg** [comment]
Hello megan,

I am.using a standard 6' micro usb cable from sparkfun and I have updated
my firmware. (I've been hammering on getting a pi working as well, with
success on that end)

**Comment by meganrobinson22** [comment]
Hey d1runberg,

We tested your program with that same cable and we weren't able to get it working either. When we tested it with shorter sparkfun cables, however, it did work. Another thing you could try is putting a brief pause (100 ms worked well for us) between RVR commands. When we added the pause we saw much better performance on the cables that were previously giving us inconsistent success.

Let me know if you still can't get it working with a shorter cable and the pause between commands!

**Comment by Jim-Konish** [comment]
Shorter cables are recommended for RVR due to aggressive USB port hardware protection.  RVR+ was altered to improve performance with longer cables.  

With no comments on this issue in 2 years, I'm closing it.
